# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: First Selenium Test Execution with GitHubActions

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: |
            export DISPLAY=:99.0
            Xvfb :99 -screen 0 1920x1080x24 &
            TEMP_DIR=$(mktemp -d)
            echo "Using temp directory for user data: $TEMP_DIR"
            mvn clean test -Dchrome.options.args="--headless,--user-data-dir=$TEMP_DIR" || echo "Test execution failed"
            rm -rf $TEMP_DIR

    - name: Upload Extent Report
      uses: actions/upload-artifact@v4
      with:
        name: extent-report
        path: test-output/extentReport.html
